### ISSUE TITLE
FoxyProxy using SOCKS5 + uBlock Origin with uncloak enabled = DNS leaks

### ISSUE THREAD

**Issue by aliron19** [foxyproxy/firefox-extension#141] opened 2021-04-06 22:16 UTC
Hi,

The following examples will use FoxyProxy Standard v7.5.1, uBlock Origin v1.34.0, and Firefox 87.0, under Windows 10 Pro 64bits.

**##################################################**
**SCENARIO 1**
**##################################################**
1. Disable FoxyProxy add-on.
2. Enable uBlock add-on.
3. Under uBlock settings, enable _[Uncloak canonical names](https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#uncloak-canonical-names)_.
4. Configure Firefox network settings to use a _Manual proxy configuration_, with a SOCKS5 proxy (for example, [TorBroswer](https://www.torproject.org/download/) provides a free socks5 proxy), and enable _Proxy DNS when using SOCKS v5_.
5. Go to https://dnsleaktest.com/ and run an _Extended test_.

RESULT: Firefox will **NOT leak** DNS. 😀

**##################################################**
**SCENARIO 2**
**##################################################**
1. Disable uBlock add-on.
2. Enable FoxyProxy add-on.
3. Add a SOCKS5 proxy server (for example, [TorBroswer](https://www.torproject.org/download/) as mentioned on the previous scenario), and enable _Send DNS through SOCKS5 proxy_.
4. Edit its patterns, and verify that is white listing _All URLs_ (wildcard *), and black listing nothing (empty section).
5. Configure FoxyProxy to use always that SOCKS5 server.
6. Configure Firefox network settings to _Use system proxy settings_ (so FoxyProxy will kick in action).
7. Go to https://dnsleaktest.com/ and run an _Extended test_.

RESULT: Firefox will **NOT leak** DNS. 😀

**##################################################**
**SCENARIO 3**
**##################################################**
1. Enable uBlock add-on.
2. Under uBlock settings, verify that _[Uncloak canonical names](https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#uncloak-canonical-names)_ is enabled.
3. Enable FoxyProxy add-on.
4. Verify that the SOCKS5 proxy server you defined on previous scenario is enabled, with its _Send DNS through SOCKS5 proxy_ option enabled too.
5. Verify its patterns, so that it's white listing _All URLs_ (wildcard *), and black listing nothing (empty section).
6. Configure FoxyProxy to use always that SOCKS5 server.
7. Configure Firefox network settings to _Use system proxy settings_ (so FoxyProxy will kick in action).
8. Go to https://dnsleaktest.com/ and run an _Extended test_.

RESULT: Firefox will **LEAK** DNS. 😓

**##################################################**
**CONCLUSIONS**
**##################################################**

1. Neither uBlock nor FoxyProxy cause DNS leaks by their own.
2. When both them are active, uBlock's uncloak feature will cause DNS leaks.

I'm not sure which one should we "blame", but as uBlock behaves as expected on scenario 1, which configuration is technically equivalent to scenario 3 (since both them are always using a SOCKS5 proxy even for DNS traffic), to me it looks more like it's FoxyProxy's "fault". 🤔

Can you please confirm if this is a FoxyProxy bug? 

If so, how can I help to debug it?

Thanks.

**Comment by Oi-Baba** [comment] 2021-06-06 21:18
I think it's actually ublock's fault because I get the same results as FoxyProxy when I use windows to configure the socks5 proxy.

One thing I noticed was that if I have DNS over HTTPS enabled, then the set DNS provider (Cloudflare for me) also shows up 
This doesn't show up in https://dnsleaktest.com/ but it does in [ExpressVPN's test](https://www.expressvpn.com/dns-leak-test).

Using Firefox's settings to manually set the proxy has no problem tho...

**Comment by jasonla** [comment] 2022-08-24 08:29
As a followup, yes I think it's uBlock origin's "fault." Although it's not a bug in uBlock really. The documentation better explains it:

https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#uncloak-canonical-names

> Important note when using extension-based proxy service: Extension-based proxy services usually are performed on the fly through a [browser API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/onRequest). In such a case, uBO's DNS queries to uncloak canonical names will NOT be caught and proxied by an extension-based proxy service. So you may want to disable this setting when using an extension-based proxy service.

**Comment by erosman** [comment] 2022-08-24 09:19
There are 2 options available for the proxy implementation in future development, each with their pros/cons:
:pushpin:  Feedback is welcomed

### On the fly [browser API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/onRequest)
- :question: Available for Firefox only
- :+1: Save user/pass in extension & import/export them
- :+1: Use user/pass for SOCKS5
- :-1: No proxy from the browser start-up until extension is loaded
- :-1: DNS leak from uBlock (or similar)
- :-1: More resource intensive


### Proxy auto-config
- :+1:  Available for Chrome & Firefox
- :question:  Save user/pass in browser settings (or system in Chrome)
- :+1: Proxy from the browser start-up
- :+1: No DNS leak from uBlock (or similar)
- :+1: Less resource intensive
- :-1: Users can't import/export user/pass with their settings
- :-1: No user/pass for SOCKS5

**Comment by jasonla** [comment] 2022-08-25 00:39
> 

Oh tough call. I don't feel like I know enough about all of the ins and outs. On the surface, the Browser Proxy auto-config looks like it has more advantages and is less resource intensive. I don't use a user/pass for my SOCKS5 server since it's in a docker container on my local network and I control the container/server.

But with the configuration change to uBlock, it's now working great for me. Maybe while this is being decided, we can add a note in the Readme for this specific scenario?

**Comment by erosman** [comment] 2023-09-23 16:59
Is the issue still occurring?

**Comment by MasterKia** [comment] 2023-09-23 19:26
I can't reproduce.

**Comment by erosman** [comment] 2023-09-23 19:30
Thank you. Therefore, I think we close this for now.

**Closed by erosman** 2023-09-23 19:30 UTC

**Comment by 20NE** [comment] 2023-10-19 00:57
firefox 118.0.2
foxyproxy 7.5.1
ublock 1.52.2
The issue still occurring! DNS stop leaking only after uBlock Origin with uncloak  disabled.
And when firefox use ECH (encrypted client hello) + DNS-over-HTTPS, always DNS leaking, whether uBlock Origin with uncloak enabled or disabled.
Pls reopen issue.

**Comment by erosman** [comment] 2023-10-19 19:13
@20NE 
We can only work on issues related to FoxyProxy. 
Issues related to other addons should be handled by their respective developers.
You can test with FoxyProxy v8 and see if there is any difference.
