### ISSUE TITLE
Unable to disable "Send DNS through SOCKS5 proxy" through GUI, nor Firefox Sync 

### ISSUE THREAD

**Issue by himura-hg** [foxyproxy/firefox-extension#35] opened 2019-09-27 00:18 UTC
Attempted to disable the **Send DNS through SOCKS5 proxy** option at GUI, no luck; when saved changes and re-opened the DNS was still there. 

Re-importing all settings did not fixed the issue, neither deleting the extension and reinstalling it, and reimporting it. 

Had to went all the way down to version 6.6.2 to import valid backup and be able to disable the DNS option for SOCK5 proxy.

**Comment by ericjung** [comment] 2019-09-27 04:37
Thanks for the bug report. I've reproduced this and am working on it now. Sorry for the trouble!

**Comment by ericjung** [comment] 2019-09-27 05:28
Fixed in version 7.3 and submitted to https://addons.mozilla.org. Since FoxyProxy is a recommended add-on by Mozilla, humans manually review all changes. So you can't get it from https://addons.mozilla.org until Mozilla releases it.

Thank you for the bug report. I will try to update this issue when Mozilla releases 7.3. You can then force an update instead of waiting for Mozilla to push it to you. Instructions to force update:

1. In firefox, go to about:addons in the address bar
2. Click the "gear" icon and select "Check for Updates"

**Closed by ericjung** 2019-09-27 05:28 UTC

**Comment by ericjung** [comment] 2019-09-27 06:55
The new version (7.3) is now available:

1. In firefox, go to about:addons in the address bar
2. Click the "gear" icon and select "Check for Updates"

**Comment by himura-hg** [comment] 2019-09-27 17:58
Thank you very much for your quick response! I'll attempt to update to 7.3
