### ISSUE TITLE
Proxy is in effect  even when disabled

### ISSUE THREAD

**Issue by amirseyedian** [foxyproxy/firefox-extension#219] opened 2023-12-12 15:17 UTC
In foxyproxy 8.6 traffic is going through tor (127.0.0.1:9050) even when foxyproxy is disabled
I did try to remove all proxies, reinstalling poxyproxy and restore default
Issue persists on new firefox profile

**Comment by erosman** [comment] 2023-12-12 16:04
I think the issue is that the Firefox proxy setting reverts to "system" and that causes Firefox to pic up TOR as the system proxy.

The issue is fixed in v8.7 (beta).
See also: https://github.com/foxyproxy/browser-extension/issues/59#issuecomment-1851798324

**Closed as completed** 2024-02-15 19:46 UTC
