### ISSUE TITLE
PAC WPAD Support

### ISSUE THREAD

**Issue by SignFinder** [foxyproxy/firefox-extension#61] opened 2020-01-17 06:36 UTC
It looks like bug, which blocked support PAC, WPAD etc, was fixed https://bugzilla.mozilla.org/show_bug.cgi?id=1443259

**Comment by BLaDZer** [comment] 2020-05-07 17:14
That would be nice. Also I will be very happy if you'll add an "auto-update over time PAC file" option. Still searching for this function but found only manual methods

**Comment by holyjak** [comment] 2021-01-07 13:01
I think you are wrong - because Firefox bug tracker is messed up. The bug mentioned is about removing deprecated APIs. The bugs that block the functionality of interest in this addon are: System Settings Proxy https://bugzilla.mozilla.org/show_bug.cgi?id=1319630 and PAC https://bugzilla.mozilla.org/show_bug.cgi?id=1396485 and WPAD https://bugzilla.mozilla.org/show_bug.cgi?id=1319631 

The were closed I believe because the API they referred was deprecated. @ericjung should perhaps create new ones that refer the new API, i.e. [`proxy.onRequest`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/onRequest) which returns [`proxy.ProxyInfo`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/ProxyInfo) which has `type` of one of `direct|http|https|socks|socks4` - i.e. we likely want `pac|wpad|system| added to the accepted types, similarly what [Chrome supports](https://developer.chrome.com/docs/extensions/reference/proxy/#proxy-modes).

**Comment by ericjung** [comment] 2021-01-07 14:12
@holyjak anyone can open tickets at bugzilla. Please feel free to do that yourself since I won’t have time to do that.

**Comment by erosman** [comment] 2022-09-11 16:21
PAC support is already added to [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released).

AFA WPAD, if someone give me a working example, than it can be worked on.

**Comment by ericjung** [comment] 2022-09-11 20:15
We don’t need WPAD support for now. But auto-refresh of PAC every X seconds would be great. I’ve used this before, when it was available in older FoxyProxy versions.

**Comment by erosman** [comment] 2022-09-12 04:16
what is the purpose of auto-refreshing a PAC every X seconds?
Does a remote PAC changes every X seconds?

PACs are by design meant to be fairly static. As a comparison, uBlock Origin has rules that get updated regularly. However, there is no function to auto-refresh rules every X seconds.
Users can manually refresh the rules, whenever wanted.

**Comment by ericjung** [comment] 2022-09-12 05:25
PACs definitely change and this is why old FoxyProxy had the ability to auto refresh (as I recall). Here is just one example:

https://raw.githubusercontent.com/petronny/gfwlist2pac/master/gfwlist.pac

This is Great Firewall of China PAC file. It is updated every day.

**Comment by erosman** [comment] 2022-09-12 06:19
There is no API to refresh a PAC. The only thing is to remove it i.e. change mode, and then reassign it i.e. change mode again.
I would imagine PAC might get refreshed in each session when Firefox starts which should be sufficient for most cases.

Users can also manually change mode if desired to refresh it.

Furthermore, with an extensive list such as GFW, the new changes are not so life-altering that would require to be constantly updated every X seconds.

**Closed** 2023-09-22 07:52 UTC
Labels: feature request, ✓Done
