### ISSUE TITLE
Proxy Authentication fails to prompt

### ISSUE THREAD

**Issue by aus** [foxyproxy/firefox-extension#66] opened 2020-01-29 16:29 UTC
My HTTP proxy requires authentication for some sites. Depending on the site, the CONNECT request to my HTTP proxy may respond with a HTTP 407 requesting either NTLM or Basic authentication. 

```
HTTP/1.1 407 Proxy Authentication Required
Proxy-Authenticate: NTLM
Proxy-Authenticate: BASIC realm="Domain_Auth"
```

Under normal Firefox operations (no addon), I am prompted with a login prompt. A valid user and password is entered and the HTTP CONNECT proxy request is retried with authentication headers. The connection then successfully establishes and the page loads.
<img width="478" alt="prompt" src="https://user-images.githubusercontent.com/549081/73375002-bfd6e480-4280-11ea-94c3-541db694062e.png">

With the FoxyProxy addon enabled but unconfigured, the connection attempt hangs indefinitely and the page never loads. 
<img width="250" alt="hang" src="https://user-images.githubusercontent.com/549081/73375010-c5342f00-4280-11ea-8c9d-c55096016ea7.png">

Some other notes:
- FoxyProxy is configured to _Turn Off (Use Firefox Settings)_.
- Firefox Proxy Settings are configured to _Use System Settings_.
- Following the packets in WireShark, I don't see any additional HTTP requests from Firefox after the 407 when FoxyProxy is enabled.
- FoxyProxy 7.4.3 
- Firefox 72.0.2
- MacOS Mojave 10.14.6
- Maybe related to #30?

**Comment by ericjung** [comment] 2020-01-30 04:28
Hi

Can you please export your FoxyProxy settings and paste them here or email them to me? Open the settings in a text editor and change any sensitive information like usernames, passwords or ip addresses.

Thank you

**Comment by aus** [comment] 2020-01-30 14:37
I've reproduced this with basically an empty config. Another interesting behavior: while stuck in the "Waiting for github.com" hang state, as soon as I disable the FoxyProxy addon, I am immediately prompted with the proxy "Authentication Required" prompt (see screenshot above).

**Config**
```json
{
  "logging": {
    "active": true,
    "maxSize": 500
  },
  "mode": "disabled",
  "browserVersion": "72.0.2",
  "foxyProxyVersion": "7.4.3",
  "foxyProxyEdition": "standard",
  "sync": true
}
```

**Comment by AndyXan** [comment] 2020-07-06 13:41
I can confirm this issue still exists which is kinda troublesome. 

```
Firefox 78.0.1 (64-bit)
FoxyProxy: Version 7.4.3
Last Updated July 6, 2020
``` 

on a refreshed plain firefox instance without any customization. Entering the Credentials into the add-proxy menu is not an option for single sign corporate credentials and not entering them does not make firefox to prompt for the credentials. 

On a side note: It works perfectly fine on google chrome, same proxy entry.

**Comment by ericjung** [comment] 2020-07-06 19:19
@AndyXan is the proxy that you are expecting prompt you a SOCKS proxy or HTTP proxy?

**Comment by AndyXan** [comment] 2020-07-08 07:28
Hello, 

it's expecting a HTTP Proxy. In fact, the same behavior happens with 2 distinct corporate proxies (one is a squid http proxy) the other one is a, well I don't actually know.

So what happens with google chrome it what I expected: 

1. Adding the Proxy in FoxyProxy with credentials blank. 
2. Accessing any Site -> Prompt for Credentials 
3. Be Happy and Access the Site's

What happens in Firefox is:

1. Adding the Proxy in FoxyProxy with credentials blank
2. Accessing any Site -> Loads forever

This happens on a freshly restored firefox installation without any config changes. This also happens when deactivation NTLM auth and other things the web suggests. Entering the Credentials in FoxyProxy when adding a the proxy works fine. However, doing so with single sign on corporate credentials is not one of my favorites.  

When I'm having time at the weekend, I might add some network-trace.

**Comment by ericjung** [comment] 2020-07-08 17:12
Thanks for the detailed reply. It is very helpful.

> When I'm having time at the weekend, I might add some network-trace.

You don't need to do that. I think I know the problem: https://github.com/foxyproxy/firefox-extension/blob/master/src/scripts/background.js#L140 is called and returns no username/password  for the proxied request. But I do not know of a way  to trigger Firefox to handle the auth portion of the request (with a prompt or whatever) once FoxyProxy has handled the request.

Also, for what it's worth, I don't think the problem you (@AndyXan) are reporting is the same as the original. In the original report, @aus  says:

> Firefox Proxy Settings are configured to Use System Settings.

System settings is not supported by FoxyProxy right now, and this is clearly indicated in the UI when selecting it. It was supported before Firefox 57, and I plan to support it again.

Anyway, if anyone knows how to fix @AndyXan's problem, (@erosman  ?), please let me know.

**Comment by erosman** [comment] 2020-07-08 18:42
https://github.com/foxyproxy/firefox-extension/blob/db61f5f936d8b17df3d8ad7dd2e9bf7460521502/src/scripts/matcher.js#L83

It seems that is the proxy doesnt send DIRECT if user/pass are not found

try:
```js
function prepareSetting(proxy) {
  const ret = {
    type: typeSet[proxy.type] || typeSet[5], // If 'direct', all other properties of this object are ignored.
    host: proxy.address, 
    port: proxy.port
  };
  proxy.username && (ret.username = proxy.username);
  proxy.password && (ret.password = proxy.password);
  proxy.proxyDNS && (ret.proxyDNS = proxy.proxyDNS); // Only useful for SOCKS
  //if ((proxy.type === PROXY_TYPE_HTTP || proxy.type === PROXY_TYPE_HTTPS) && proxy.username && proxy.password) {
    // Using wireshark, I do not see this header being sent, contrary to
    // https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/ProxyInfo
    //ret.proxyAuthorizationHeader = 'Basic ' + btoa(proxy.username + ":" + proxy.password);
  //}
  
  return ret.username && ret.password ? ret : {type: 'direct'};
}
```

**Comment by ericjung** [comment] 2020-07-08 20:50
@erosman, thank you. I see the difference is:

`return ret.username && ret.password ? ret : {type: 'direct'};`

But this will break "open proxies" -- proxies that do not require username/password. In such cases, the user will leave username/password blank and FoxyProxy would return 'direc't (no proxy).

**Comment by erosman** [comment] 2020-07-08 21:02
> But this will break "open proxies" -- proxies that do not require username/password. In such cases, the user will leave username/password blank and FoxyProxy will return 'direc't (no proxy) when it should return type, host, port

How can the extension differentiate between "open proxies" & proxies that user hasn't entered u/p for (since FP is not listening to onAuthRequired)?

**Comment by ericjung** [comment] 2020-07-08 22:02
> How can the extension differentiate between "open proxies" & proxies that user hasn't entered u/p for (since FP is not listening to onAuthRequired)?

It can't, although are you suggesting that using onAuthRequired would fix this? I'm guessing yes.

**Comment by erosman** [comment] 2020-07-09 04:32
> It can't,

Ergo the dilemma

> are you suggesting that using onAuthRequired would fix this

Sadly, the 2 separate async API don't easily work together and can result in delayed connections.

**Comment by ericjung** [comment] 2020-07-09 16:17
@erosman , what if I remove username/password from `prepareSetting()` -- even when user specifies username/password in UI. Then use `onAuthRequired()` to supply username/password.

**Comment by erosman** [comment] 2020-07-09 16:54
> what if I remove username/password from prepareSetting() -- even when user specifies username/password in UI. Then use onAuthRequired() to supply username/password.

There is already `onAuthRequired()` but it is bypassed

https://github.com/foxyproxy/firefox-extension/blob/master/src/scripts/background.js#L48

There would be delays in connections and cant do SOCKS authentication so SOCKS proxies will fail.

You will have to test and see but it may create more issues.

How many people use open proxies?
What exactly happens during an open proxy connection?


I think it is better to check above first and then decide.

**Comment by githuborer** [comment] 2020-09-11 07:40
I ran into this bug and made a small proxy.pac config file for firefox. Its working

**Comment by ericjung** [comment] 2020-09-11 19:55
I think I found a fix for this. FoxyProxy, when disabled, is [not removing its authentication listener](https://github.com/foxyproxy/firefox-extension/blob/master/src/scripts/background.js#L48). I will add that to the next release.

**Comment by jeanmonet** [comment] 2021-11-03 23:10
Unfortunately BasicAuth does not currently work with FoxyProxy v7.5.1 (Firefox 93). The username / password fields do not work.

**Comment by ericjung** [comment] 2021-11-04 03:49
Can you explain what you mean by “the username / passwords fields do not work”?

**Comment by jeanmonet** [comment] 2021-11-04 12:24
> Can you explain what you mean by “the username / passwords fields do not work”?

A HTTP proxy (Tinyproxy) configured with BasicAuth (with a user & password), ie http://user:pass@proxy_ip:port. When entering the username & passowrd in the username & passoword fields provided by FoxyProxy underneath the IP and port fields (when adding a new proxy to the list), well, the connection does not happen.

It works if I disable the plugin and use Firefox's native proxy settings, entering the info via the username/password popup upon first connection.

It also works with FoxyProxy if there is no BasicAuth configuration on the proxy server.

Hope this helps.

**Comment by ericjung** [comment] 2021-12-08 13:53
Unfortunately I’ll need the address and un/pw to your proxy to debug this. I suspect it is a problem with your configuration since other proxy servers are working. Contact me at support@getfoxyprpxy.org with the private info. Thanks.

**Comment by AkikoOrenji** [comment] 2022-02-27 22:31
I am having the same problem with our corprorate proxy. As soon as the plugin is enabled firefox no longer displays authentication prompts from our proxy. After disabling the plugin the corporate proxy prompts appear. I would have through the setting 'Turn Off (Use Firefox Settings) would effectively disable the plugin but it doesn't. 
Once firefox has cached the credentials to the corporate proxy its no longer an issue until the credentials expire and then its breaks all internet access as you can no longer authenticate to the corporate proxy.

**Comment by bls4** [comment] 2022-05-18 18:48
1. Close firefox, 
2. Go to this folder "**browser-extension-data**" and delete it.
3. Reopen firefox, now proxy is working.

C:\Users\MyUser\AppData\Roaming\Mozilla\Firefox\Profiles\12e2zl2d.default-release-3\browser-extension-data

**Comment by mvrk69** [comment] 2022-08-24 18:47
Any news about this? I just run into the same bug with my corporate proxy, and i can't put user/pwd in the foxyproxy config because pwd is not static, uses tokens.

**Comment by ericjung** [comment] 2022-08-24 21:30
@mvrk69  we are rewriting FoxyProxy right now. This problem will be fixed in the next release, 8.0.
@erosman  ping

**Comment by erosman** [comment] 2022-08-24 22:02
There is no `onAuthRequired` listener in v8.0 and all `onAuthRequired` are handled by the browser.
Eric, you can even remove it from current FP if you want.

When a URL matches a pattern or FP is set to forward all to a single proxy, then ...
- If that proxy has user/pass, network request is sent through the proxy with the user/pass. In this case there wont be any credentials request since user/pass are already sent.
- If that proxy doesn't have a user/pass, network request is sent through the proxy without any user/pass. If user/pass is required, then the browser will handle it.

**Comment by erosman** [comment] 2022-09-14 17:23
Authentication process is re-written in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released) which should fix this issue.

**Closed** 2023-09-22 08:01 UTC
Labels: ✓Done
